name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - run: pacman -Sy --needed --noconfirm base-devel git meson wayland-protocols wlroots xorg-xwayland
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build wlroots
        run: meson setup build && ninja -C build
        working-directory: ./wlroots
      
      - name: Build dwl
        run: make
        working-directory: ./dwl
          
