# This is a basic workflow to help you get started with Actions

name: Sync

on:
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'dwl/dwl'
          github-server-url: 'https://codeberg.org'
