name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}
  
      - run: pacman -Sy --needed --noconfirm base-devel git meson wayland-protocols wlroots xorg-xwayland
      
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build wlroots
        run: meson setup build && ninja -C build
        working-directory: wlroots
      
      - name: Build dwl
        run: |
          echo 'WLR_INCS = -I/usr/include/pixman-1 -I/usr/include/elogind -I/usr/include/libdrm -I$(PWD)/../wlroots/include' >> config.mk
          echo 'WLR_LIBS = -Wl,-rpath,$(PWD)/../wlroots/build -L$(PWD)/../wlroots/build -lwlroots-0.19' >> config.mk
          echo 'XWAYLAND = -DXWAYLAND' >> config.mk
          echo 'XLIBS = xcb xcb-icccm' >> config.mk
          make
        working-directory: dwl

      - uses: actions/upload-artifact@v4
        with:
          path: dwl/dwl

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dwl/dwl
