name: Sync

on:
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'dwl/dwl'
          ref: 'main'
          github-server-url: 'https://codeberg.org'
