name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    defaults:
      run:
        working-directory: .dwl
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: pacman --noconfirm -Sy make wayland-protocols wlroots xorg-xwayland
      - name: Build
        run: make
        working-directory: ./dwl
          
