name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - run: pacman --noconfirm -Sy git make wayland-protocols wlroots xorg-xwayland
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: make
        working-directory: ./dwl
          
